### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by wohaiwo** [SwallowLong/IFE-2017#1]
- 这里可以在项目setting里面添加添加URL  便于点击 你也可以在readme.md里面添加地址
 ![default](https://cloud.githubusercontent.com/assets/7277608/24068360/9e3913e0-0bc7-11e7-967a-cfe1492117db.png)
- 然后你这个地址http://htmlpreview.github.io/?https://github.com/SwallowLong/IFE-2017/blob/master/IFE-2017/index.html 是怎么配出来的  理论上 不是 https://swallowlong.github.io/IFE-2017/index.html 里面跳转的吗？ 
- 进去之后点击一个demo1 然后就没有返回到之前的主页

**Comment by SwallowLong** [comment]
> 这里可以在项目setting里面添加添加URL 便于点击 你也可以在readme.md里面添加地址
> default
> 然后你这个地址http://htmlpreview.github.io/?https://github.com/SwallowLong/IFE-2017/blob/master/IFE-2017/index.html 是怎么配出来的 理论上 不是 https://swallowlong.github.io/IFE-2017/index.html 里面跳转的吗？
> 进去之后点击一个demo1 然后就没有返回到之前的主页


@wohaiwo 

* 
 ![default](https://cloud.githubusercontent.com/assets/18194863/24070847/e679c950-0bff-11e7-96f9-6bca8543a8f0.png)

* 这个地址我是在IFE提交作业看见别人很多是这样的，就试了下在index.htm的URL之前加http://htmlpreview.github.io/? 就可以跳转， 这个 https://swallowlong.github.io/IFE-2017/IFE-2017/ 是imooc上说的先创建了新的gh-pages分支后，就可以的，我实验了下不gh-pages直接 https://swallowlong.github.io/IFE-2017/IFE-2017/index.html 这样就会报错404

* 返回的问题我在想想，看看能不能搞好

**Comment by wohaiwo** [comment]
如果不添加 gh-pages分支  github只是会把你这个项目当成一个 在线的仓库，而不会进行在线编译出来 
http://htmlpreview.github.io/?这里在他那个页面这行了页面的编译过程  结果会导致你的a标签跳转是会出现问题的

**Comment by wohaiwo** [comment]
然后 你真的会git了吗？ git要好好去学习   例如 
- 如何撤销本地版本库git add 的操作
- 当你一不小 git commit 到你当前本地分支的时候 如果撤销
- 当你开发一般 突然越到紧急bug 要修复， 但是当前的分支没有开发完成， 无法提交上去 如何解决这个问题
- 当github上面的版本库版本比你本地的新 如果解决

**Comment by SwallowLong** [comment]
@wohaiwo 
* 但我看你的博客的那个repository里面都没gh-pages的分支啊
* git add和git commit 的我一般是rm或者git rm，当然也会通过git log 和git reflog与git reset --hard来搞
* 可以先将其git stash 在git stash pop回来
* 这个应该git pull 就可以吧
* 我自己记了些命令行 https://swallowlong.github.io/ ,你看暂时有这些可以否，可以的话，我就继续去搞IFE了，搞git的时候还把task7删了，我应该继续了....慢了好多了

**Comment by SwallowLong** [comment]
好几把惨的

**Comment by wohaiwo** [comment]
![githubpage](https://cloud.githubusercontent.com/assets/7277608/24090251/5814c5d6-0d79-11e7-9b84-862b4aa50290.gif)
- setting 里面可以设置的 
- 尽量把你的代码放在一个工程下面 然后发到GitHub pages 这样我有空 可以给你 codereview @SwallowLong
